/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author kavishna
 */
public class calculatorUI extends javax.swing.JFrame {

    /**
     * Creates new form calculatorUI
     */
    public calculatorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottomPanel = new javax.swing.JPanel();
        jpanel0 = new javax.swing.JPanel();
        lable0 = new javax.swing.JLabel();
        jpanel1 = new javax.swing.JPanel();
        lable3 = new javax.swing.JLabel();
        jpanel2 = new javax.swing.JPanel();
        lable4 = new javax.swing.JLabel();
        jpanel3 = new javax.swing.JPanel();
        lable5 = new javax.swing.JLabel();
        jpanel4 = new javax.swing.JPanel();
        lable7 = new javax.swing.JLabel();
        jpanel5 = new javax.swing.JPanel();
        lable8 = new javax.swing.JLabel();
        jpanel6 = new javax.swing.JPanel();
        lable9 = new javax.swing.JLabel();
        jpanel7 = new javax.swing.JPanel();
        lable11 = new javax.swing.JLabel();
        jpanel8 = new javax.swing.JPanel();
        lable12 = new javax.swing.JLabel();
        jpanel9 = new javax.swing.JPanel();
        lable13 = new javax.swing.JLabel();
        dot = new javax.swing.JPanel();
        dotLable = new javax.swing.JLabel();
        equal = new javax.swing.JPanel();
        lable2 = new javax.swing.JLabel();
        plus = new javax.swing.JPanel();
        lable6 = new javax.swing.JLabel();
        minus = new javax.swing.JPanel();
        lable10 = new javax.swing.JLabel();
        multi = new javax.swing.JPanel();
        lable14 = new javax.swing.JLabel();
        devide = new javax.swing.JPanel();
        lable18 = new javax.swing.JLabel();
        presentage = new javax.swing.JPanel();
        lable17 = new javax.swing.JLabel();
        clear = new javax.swing.JPanel();
        lable15 = new javax.swing.JLabel();
        plusorminus = new javax.swing.JPanel();
        lable16 = new javax.swing.JLabel();
        display = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bottomPanel.setBackground(new java.awt.Color(85, 84, 86));

        jpanel0.setBackground(new java.awt.Color(126, 126, 127));

        lable0.setBackground(new java.awt.Color(255, 255, 255));
        lable0.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable0.setForeground(new java.awt.Color(255, 255, 255));
        lable0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable0.setText("0");

        javax.swing.GroupLayout jpanel0Layout = new javax.swing.GroupLayout(jpanel0);
        jpanel0.setLayout(jpanel0Layout);
        jpanel0Layout.setHorizontalGroup(
            jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel0Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lable0)
                .addGap(45, 45, 45))
        );
        jpanel0Layout.setVerticalGroup(
            jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable0, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanel1.setBackground(new java.awt.Color(126, 126, 127));

        lable3.setBackground(new java.awt.Color(255, 255, 255));
        lable3.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable3.setForeground(new java.awt.Color(255, 255, 255));
        lable3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable3.setText("1");

        javax.swing.GroupLayout jpanel1Layout = new javax.swing.GroupLayout(jpanel1);
        jpanel1.setLayout(jpanel1Layout);
        jpanel1Layout.setHorizontalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lable3)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpanel1Layout.setVerticalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jpanel2.setBackground(new java.awt.Color(126, 126, 127));

        lable4.setBackground(new java.awt.Color(255, 255, 255));
        lable4.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable4.setForeground(new java.awt.Color(255, 255, 255));
        lable4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable4.setText("2");

        javax.swing.GroupLayout jpanel2Layout = new javax.swing.GroupLayout(jpanel2);
        jpanel2.setLayout(jpanel2Layout);
        jpanel2Layout.setHorizontalGroup(
            jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lable4)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jpanel2Layout.setVerticalGroup(
            jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jpanel3.setBackground(new java.awt.Color(126, 126, 127));

        lable5.setBackground(new java.awt.Color(255, 255, 255));
        lable5.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable5.setForeground(new java.awt.Color(255, 255, 255));
        lable5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable5.setText("3");

        javax.swing.GroupLayout jpanel3Layout = new javax.swing.GroupLayout(jpanel3);
        jpanel3.setLayout(jpanel3Layout);
        jpanel3Layout.setHorizontalGroup(
            jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lable5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel3Layout.setVerticalGroup(
            jpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jpanel4.setBackground(new java.awt.Color(126, 126, 127));

        lable7.setBackground(new java.awt.Color(255, 255, 255));
        lable7.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable7.setForeground(new java.awt.Color(255, 255, 255));
        lable7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable7.setText("4");

        javax.swing.GroupLayout jpanel4Layout = new javax.swing.GroupLayout(jpanel4);
        jpanel4.setLayout(jpanel4Layout);
        jpanel4Layout.setHorizontalGroup(
            jpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lable7)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpanel4Layout.setVerticalGroup(
            jpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jpanel5.setBackground(new java.awt.Color(126, 126, 127));

        lable8.setBackground(new java.awt.Color(255, 255, 255));
        lable8.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable8.setForeground(new java.awt.Color(255, 255, 255));
        lable8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable8.setText("5");

        javax.swing.GroupLayout jpanel5Layout = new javax.swing.GroupLayout(jpanel5);
        jpanel5.setLayout(jpanel5Layout);
        jpanel5Layout.setHorizontalGroup(
            jpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lable8)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpanel5Layout.setVerticalGroup(
            jpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jpanel6.setBackground(new java.awt.Color(126, 126, 127));

        lable9.setBackground(new java.awt.Color(255, 255, 255));
        lable9.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable9.setForeground(new java.awt.Color(255, 255, 255));
        lable9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable9.setText("6");

        javax.swing.GroupLayout jpanel6Layout = new javax.swing.GroupLayout(jpanel6);
        jpanel6.setLayout(jpanel6Layout);
        jpanel6Layout.setHorizontalGroup(
            jpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lable9)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jpanel6Layout.setVerticalGroup(
            jpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jpanel7.setBackground(new java.awt.Color(126, 126, 127));

        lable11.setBackground(new java.awt.Color(255, 255, 255));
        lable11.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable11.setForeground(new java.awt.Color(255, 255, 255));
        lable11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable11.setText("7");

        javax.swing.GroupLayout jpanel7Layout = new javax.swing.GroupLayout(jpanel7);
        jpanel7.setLayout(jpanel7Layout);
        jpanel7Layout.setHorizontalGroup(
            jpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lable11)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jpanel7Layout.setVerticalGroup(
            jpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jpanel8.setBackground(new java.awt.Color(126, 126, 127));

        lable12.setBackground(new java.awt.Color(255, 255, 255));
        lable12.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable12.setForeground(new java.awt.Color(255, 255, 255));
        lable12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable12.setText("8");

        javax.swing.GroupLayout jpanel8Layout = new javax.swing.GroupLayout(jpanel8);
        jpanel8.setLayout(jpanel8Layout);
        jpanel8Layout.setHorizontalGroup(
            jpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lable12)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpanel8Layout.setVerticalGroup(
            jpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jpanel9.setBackground(new java.awt.Color(126, 126, 127));

        lable13.setBackground(new java.awt.Color(255, 255, 255));
        lable13.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable13.setForeground(new java.awt.Color(255, 255, 255));
        lable13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable13.setText("9");

        javax.swing.GroupLayout jpanel9Layout = new javax.swing.GroupLayout(jpanel9);
        jpanel9.setLayout(jpanel9Layout);
        jpanel9Layout.setHorizontalGroup(
            jpanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lable13)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpanel9Layout.setVerticalGroup(
            jpanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        dot.setBackground(new java.awt.Color(126, 126, 127));

        dotLable.setBackground(new java.awt.Color(255, 255, 255));
        dotLable.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        dotLable.setForeground(new java.awt.Color(255, 255, 255));
        dotLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dotLable.setText(".");

        javax.swing.GroupLayout dotLayout = new javax.swing.GroupLayout(dot);
        dot.setLayout(dotLayout);
        dotLayout.setHorizontalGroup(
            dotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dotLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(dotLable)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        dotLayout.setVerticalGroup(
            dotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dotLayout.createSequentialGroup()
                .addComponent(dotLable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        equal.setBackground(new java.awt.Color(253, 158, 43));

        lable2.setBackground(new java.awt.Color(255, 255, 255));
        lable2.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable2.setForeground(new java.awt.Color(255, 255, 255));
        lable2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable2.setText("=");

        javax.swing.GroupLayout equalLayout = new javax.swing.GroupLayout(equal);
        equal.setLayout(equalLayout);
        equalLayout.setHorizontalGroup(
            equalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, equalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lable2)
                .addGap(17, 17, 17))
        );
        equalLayout.setVerticalGroup(
            equalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equalLayout.createSequentialGroup()
                .addComponent(lable2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        plus.setBackground(new java.awt.Color(253, 158, 43));

        lable6.setBackground(new java.awt.Color(255, 255, 255));
        lable6.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable6.setForeground(new java.awt.Color(255, 255, 255));
        lable6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable6.setText("+");

        javax.swing.GroupLayout plusLayout = new javax.swing.GroupLayout(plus);
        plus.setLayout(plusLayout);
        plusLayout.setHorizontalGroup(
            plusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plusLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lable6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plusLayout.setVerticalGroup(
            plusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        minus.setBackground(new java.awt.Color(253, 158, 43));

        lable10.setBackground(new java.awt.Color(255, 255, 255));
        lable10.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable10.setForeground(new java.awt.Color(255, 255, 255));
        lable10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable10.setText("-");

        javax.swing.GroupLayout minusLayout = new javax.swing.GroupLayout(minus);
        minus.setLayout(minusLayout);
        minusLayout.setHorizontalGroup(
            minusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lable10)
                .addGap(18, 18, 18))
        );
        minusLayout.setVerticalGroup(
            minusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        multi.setBackground(new java.awt.Color(253, 158, 43));

        lable14.setBackground(new java.awt.Color(255, 255, 255));
        lable14.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable14.setForeground(new java.awt.Color(255, 255, 255));
        lable14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable14.setText("×");

        javax.swing.GroupLayout multiLayout = new javax.swing.GroupLayout(multi);
        multi.setLayout(multiLayout);
        multiLayout.setHorizontalGroup(
            multiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lable14)
                .addGap(18, 18, 18))
        );
        multiLayout.setVerticalGroup(
            multiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multiLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lable14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        devide.setBackground(new java.awt.Color(253, 158, 43));

        lable18.setBackground(new java.awt.Color(255, 255, 255));
        lable18.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable18.setForeground(new java.awt.Color(255, 255, 255));
        lable18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable18.setText("÷");

        javax.swing.GroupLayout devideLayout = new javax.swing.GroupLayout(devide);
        devide.setLayout(devideLayout);
        devideLayout.setHorizontalGroup(
            devideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, devideLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lable18)
                .addGap(18, 18, 18))
        );
        devideLayout.setVerticalGroup(
            devideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        presentage.setBackground(new java.awt.Color(101, 100, 102));

        lable17.setBackground(new java.awt.Color(255, 255, 255));
        lable17.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable17.setForeground(new java.awt.Color(255, 255, 255));
        lable17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable17.setText("0");

        javax.swing.GroupLayout presentageLayout = new javax.swing.GroupLayout(presentage);
        presentage.setLayout(presentageLayout);
        presentageLayout.setHorizontalGroup(
            presentageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, presentageLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lable17)
                .addGap(17, 17, 17))
        );
        presentageLayout.setVerticalGroup(
            presentageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(presentageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clear.setBackground(new java.awt.Color(101, 100, 102));

        lable15.setBackground(new java.awt.Color(255, 255, 255));
        lable15.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        lable15.setForeground(new java.awt.Color(255, 255, 255));
        lable15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable15.setText("AC");

        javax.swing.GroupLayout clearLayout = new javax.swing.GroupLayout(clear);
        clear.setLayout(clearLayout);
        clearLayout.setHorizontalGroup(
            clearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clearLayout.createSequentialGroup()
                .addComponent(lable15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        clearLayout.setVerticalGroup(
            clearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        plusorminus.setBackground(new java.awt.Color(101, 100, 102));

        lable16.setBackground(new java.awt.Color(255, 255, 255));
        lable16.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lable16.setForeground(new java.awt.Color(255, 255, 255));
        lable16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable16.setText("±");

        javax.swing.GroupLayout plusorminusLayout = new javax.swing.GroupLayout(plusorminus);
        plusorminus.setLayout(plusorminusLayout);
        plusorminusLayout.setHorizontalGroup(
            plusorminusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plusorminusLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lable16)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        plusorminusLayout.setVerticalGroup(
            plusorminusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plusorminusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        display.setFont(new java.awt.Font("Courier New", 0, 48)); // NOI18N
        display.setForeground(new java.awt.Color(255, 255, 255));
        display.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        display.setText("8");

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plusorminus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(presentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(devide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addComponent(jpanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bottomPanelLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jpanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jpanel0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bottomPanelLayout.createSequentialGroup()
                                .addComponent(jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(equal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(minus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusorminus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(devide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(presentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addComponent(jpanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addComponent(jpanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addComponent(multi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addComponent(jpanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(equal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpanel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel clear;
    private javax.swing.JPanel devide;
    private javax.swing.JLabel display;
    private javax.swing.JPanel dot;
    private javax.swing.JLabel dotLable;
    private javax.swing.JPanel equal;
    private javax.swing.JPanel jpanel0;
    private javax.swing.JPanel jpanel1;
    private javax.swing.JPanel jpanel2;
    private javax.swing.JPanel jpanel3;
    private javax.swing.JPanel jpanel4;
    private javax.swing.JPanel jpanel5;
    private javax.swing.JPanel jpanel6;
    private javax.swing.JPanel jpanel7;
    private javax.swing.JPanel jpanel8;
    private javax.swing.JPanel jpanel9;
    private javax.swing.JLabel lable0;
    private javax.swing.JLabel lable10;
    private javax.swing.JLabel lable11;
    private javax.swing.JLabel lable12;
    private javax.swing.JLabel lable13;
    private javax.swing.JLabel lable14;
    private javax.swing.JLabel lable15;
    private javax.swing.JLabel lable16;
    private javax.swing.JLabel lable17;
    private javax.swing.JLabel lable18;
    private javax.swing.JLabel lable2;
    private javax.swing.JLabel lable3;
    private javax.swing.JLabel lable4;
    private javax.swing.JLabel lable5;
    private javax.swing.JLabel lable6;
    private javax.swing.JLabel lable7;
    private javax.swing.JLabel lable8;
    private javax.swing.JLabel lable9;
    private javax.swing.JPanel minus;
    private javax.swing.JPanel multi;
    private javax.swing.JPanel plus;
    private javax.swing.JPanel plusorminus;
    private javax.swing.JPanel presentage;
    // End of variables declaration//GEN-END:variables
}
